visual:
  num_points: 8
  max_components: 1  # BUSI default. (lung-like can be 2)
  # thresholds / params later when DenseCRF is implemented
  crf:
    enabled: true

text:
  question_template: "Question: {}, Answer is:"
  question: "What is the shape of breast tumor and where is it located?"
  vqa_enabled: true
  gpt_enabled: false

  vqa_model_id: "Salesforce/blip-vqa-base"
  gpt_model: "gpt-4o-mini"

