prompts:
  visual:
    class_text: "breast tumor"

    num_points: 8
    max_components: 1
    points_seed: 42
    saliency_threshold: 0.3

    crf:
      enabled: false   
      iters: 5

    cam:
      target_layer: "visual.trunk.blocks.10.norm"
      use_vit_reshape: true


  text:
    question_template: "Question: {}, Answer is:"
    question: "What is the shape of breast tumor and where is it located?"
    vqa_enabled: true
    gpt_enabled: false

    vqa_model_id: "Salesforce/blip-vqa-base"
    gpt_model: "gpt-4o-mini"

